# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='examples',
            field=models.TextField(),
        ),
    ]
