# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170603_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='pub_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='title',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
