# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20170603_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
